/*eslint-disable*/
define('openjs', function () {

    !function(n,t){function r(n,t){return f.cleanObj.toString.call(n).slice(8,-1)===t}function e(n,t){for(var r,e,i=n.split(":"),s=i.pop().split("/"),a=f;r=s.shift();)"bdbox"!==r&&(e=r,s.length&&(a=a[r]=a[r]||{}));var c=p[n]={exports:{}},u=f.isFunction(t)?t.apply(c,[o,c.exports,c,f]):t;u&&(c.exports=u),a[e]=c.exports
    }function o(n){var t=p[n];if(t)return t.exports;throw"module "+n+" is undefined"}function i(){v.forEach(function(n){n()}),v.length=0,h=!0}function s(n,t,r){if("object"==typeof n){var e,o,i=a(n);if(r=r||n,"array"===i||"arguments"===i||"nodelist"===i){for(e=0,o=n.length;o>e;e++)if(t.call(r,n[e],e,n)===!1)return
    }else for(e in n)if(n.hasOwnProperty(e)&&t.call(r,n[e],e,n)===!1)return}}function a(n){var t;return null==n?t=String(n):(t=Object.prototype.toString.call(n).toLowerCase(),t=t.substring(8,t.length-1)),t}function c(t){var r=t.success||x,e={imageUrl:"",mediaType:"all",title:"",content:"",linkUrl:location.href},o=t.error||x;
    return f.isFunction(t.success)&&(r="_xSHARE_SUCCESS_"+f.getId(),n[r]=t.success,e.success=r),f.isFunction(t.error)&&(o="_xSHARE_FAIL_"+f.getId(),n[o]=t.error,e.error=o),f.each(t,function(n,r){"success"!==r&&"error"!==r&&(r in _?r=_[r]:"content"!==r||t.title||(e.title=n),e[r]=n)}),f.isArray(e.mediaType)&&(e.mediaType="all"),n.BoxShareData||(n.BoxShareData={successcallback:r,errorcallback:o,options:e}),e
    }var u=+new Date,d=(u+"").slice(-3),l=navigator.userAgent,f={isBox:/ baiduboxapp\//i.test(l),isIOS:/(iPhone|iPod|iPad)/.test(l),isAndroid:/(Android);?\s+([\d.]+)?/.test(l),getId:function(){return d++},emptyArr:[],emptyFn:function(){},cleanObj:{},byId:function(n){return f.isString(n)?t.getElementById(n):n
    },toArray:function(n){return f.emptyArr.slice.call(n)},$:function(n,r){return r=r&&1===r.nodeType?r:t,f.toArray(r.querySelectorAll(n))}};"Function,String,Array,Number,RegExp".replace(/[^, ]+/g,function(n){f["is"+n]=function(t){return r(t,n)}}),f.isBoolean=function(n){return n===!0||n===!1},f.isObject=function(n){return"object"==typeof n
    },f.isUndefined=function(n){return void 0===n},f.isWindow=function(n){return null!=n&&n==n.window},f.isPlainObject=function(n){return f.isObject(n)&&!f.isWindow(n)&&Object.getPrototypeOf(n)==Object.prototype};var p={};f.define=e;var m=function(n,t,r){for(var e,o,i=n.split("."),s=r||m;e=i.shift();)"Box"!==e&&(o=e,i.length&&(s=s[e]=s[e]||{}));
    return s[o]=t||{},s[o]},v=[],h=!1;m.init=function(n){return"function"!=typeof n?this:(h?n():v.push(n),this)},"complete,loaded,interactive".indexOf(t.readyState)>-1&&t.body?i():t.addEventListener("DOMContentLoaded",i,!1),e("common:bdbox/utils/getVersion",function(t,r,e){var o=function(){var t=0;if(n.baiduboxapp_version)t=n.baiduboxapp_version;
    else{var r,e=navigator.userAgent;(r=/([\d+.]+)_(?:diordna|enohpi)_/.exec(e))?(r=r[1].split("."),t=r.reverse().join(".")):(r=/baiduboxapp\/([\d+.]+)/.exec(e))&&(t=r[1])}return o=function(){return t},t};e.exports=o}),e("common:bdbox/utils/version_compare",function(n,t,r){var e=function(n,t){t+="",n+="";
    for(var r=n.split("."),e=t.split("."),o=0,i=Math.max(r.length,e.length);i>o;o++){if(r[o]&&!e[o]&&parseInt(r[o])>0||parseInt(r[o])>parseInt(e[o]))return 1;if(e[o]&&!r[o]&&parseInt(e[o])>0||parseInt(r[o])<parseInt(e[o]))return-1}return 0};r.exports=e}),e("common:bdbox/ios/invokeApp",function(r,e,o,i){o.exports=function(r,e,o){if(r&&i.isBox){var s=[];
    if(i.isFunction(e))o=e;else for(var a in e)s.push(a+"="+e[a]);if(i.isFunction(o)){var c="_bdbox_js_"+i.getId();n[c]=function(){o.apply(n,[].slice.call(arguments,0))},s.push("func="+c)}else o&&s.push("func="+o);s="baiduboxapp://"+r+"?"+s.join("&");var u="_bdbox_ios_jsbridge",d=t.getElementById(u);d?d.src=s:(d=t.createElement("iframe"),d.style.display="none",d.id=u,d.src=s,(t.body||t.getElementsByTagName("body")[0]).appendChild(d))
    }}}),e("common:bdbox/android/invokeApp",function(t,r,e,o){function i(t,r,e){if(e&&!o.isArray(e)&&(e=Array.prototype.slice.call(arguments,0).slice(2)),n[t]&&n[t][r]){var i=n[t][r].apply(n[t],e);return{error:0,result:i,__from:"js"}}var u=c();if(a(u,4.8)>=0){var d=s(t,r,e);return d=d?JSON.parse(d):{},d.__from="app",d
    }if("4.7.1"===u||"4.7"==u){var l=s(t,r,e);return{error:0,result:l,__from:"app4.7"}}return{error:200}}function s(t,r,e){if(!o.isBox)return{error:201};var i={obj:t,func:r,args:e?e:[]};try{return n.prompt("BdboxApp:"+JSON.stringify(i))}catch(s){return{error:201}}}var a=t("common:bdbox/utils/version_compare"),c=t("common:bdbox/utils/getVersion");
    e.exports=i}),e("common:bdbox/utils/detect",function(t,r,e,o){function i(t){var r={name:"unknown",version:0};this===n||this.os||(this.os=r),t=t||navigator.userAgent;var e={Weibo:/weibo/i,Wechat:/micromessenger\//i,QQ:/QQ\//};for(var o in e)e.hasOwnProperty(o)&&(r["is"+o]=e[o].test(t));r.isUC=t.match(/UC/)||n.ucweb||n.ucbrowser;
    var i=t.match(/(Android);?\s+([\d.]+)?/);if(i)return r.android=!0,r.version=i[2],r.name="android",r;var s=t.match(/(iPad).*OS\s([\d_]+)/),a=t.match(/(iPod)(.*OS\s([\d_]+))?/),c=!s&&t.match(/(iPhone\sOS)\s([\d_]+)/);return c&&!a?(r.ios=r.iphone=!0,r.version=c[2].replace(/_/g,"."),r.name="ios",r):s?(r.ios=r.ipad=!0,r.name="ios",r.version=s[2].replace(/_/g,"."),r):a?(r.name="ios",r.ios=r.ipod=!0,r.version=a[3]?a[3].replace(/_/g,"."):null,r):r
    }i.apply(o),e.exports=i});var b=encodeURIComponent;f.version=f.utils.getVersion(),f.version_compare=f.utils.version_compare,f.each=s,f.type=a,f.canI=function(n,t,r){return f.version_compare(f.version,n)>=0?f.isFunction(t)&&t():f.isFunction(r)&&r(),f};var g="android"===f.os.name?function(n,t){f.isObject(n)&&(t=n,n=n.url,delete t.url);
    var r=["S.bdsb_light_start_url="+b(n)];if(f.isObject(t)){var e={color:"i.extra_actionbar_color_id",appid:"S.bdsb_wallet_appid"};s(t,function(n,t){"color"===t&&(n=4278190080|parseInt("0x"+n)),t=e[t]||t,r.push(t+"="+n)})}r=r.join(";"),f.android.invokeApp("Bdbox_android_utils","command",[JSON.stringify({intent:"intent:#Intent;"+r+";end","class":"com.baidu.searchbox.wallet.WalletServiceActivity",min_v:"16783629",mode:"0"})])
    }:function(n,t){f.isObject(n)&&(t=n,n=n.url,delete t.url);var r={openurl:b(n),minver:"5.3.0.0",isla:0,opentype:1,append:0,rbtnstyle:2};if(f.isObject(t)){var e={color:"barcolor"};s(t,function(n,t){t=e[t]||t,r[t]=n})}r.appid&&(r.isla=1),f.ios.invokeApp("easybrowse",r)};if(f.o2o=g,"android"===f.os.name?(m("card",{query:function(n,t){if(m.version_compare(m.version,"5.0")<0)return this;
    var r,e;m.isArray(n)?r=[JSON.stringify(n)]:(e=m.toArray(arguments),t=e.pop(),m.isFunction(t)?r=e:(r=m.toArray(arguments),t=null),r=[JSON.stringify(r)]);var o=m.android.invokeApp("Bdbox_android_card","mquery",r);return o=0===o.error&&o.result?JSON.parse(o.result):!1,m.isFunction(t)&&t(o),o},add:function(t,r){if(m.version_compare(m.version,"5.0")<0)return this;
    var e,o;m.isString(t)?e=[t]:m.isArray(t)?e=[JSON.stringify(t)]:(o=m.toArray(arguments),r=o.pop(),m.isFunction(r)?e=o:(e=m.toArray(arguments),r=null),e=[JSON.stringify(e)]);var i=null;if(m.version_compare(m.version,"5.5")>=0){var s="";m.isFunction(r)&&(s="__box_card_"+m.getId(),n[s]=function(n){var t=JSON.parse(n),e=!1;
    for(var o in t){e=t[o].st;break}r(e)}),i=m.android.invokeApp("Bdbox_android_card","madd",e.concat([s,0]))}else i=m.android.invokeApp("Bdbox_android_card","madd",e);return i}}),!function(){function n(n,r,e){if(f.version_compare(f.version,"4.6")<0)return this;n="invokeWz"===e?[f.isString(n)?n:JSON.stringify(n),"{}"]:[f.isString(n)?n:JSON.stringify(n)];
    var o=f.android.invokeApp(t,e,n);return o="queryWzStatus"===e?0===o.error?0|o.result:0:0===o.error,f.isFunction(r)&&r(o),o}var t="Bdbox_android_xsearch";m("lightapp",{add:function(t,r){return n.call(this,t,r,"addWz")},query:function(t,r){return n.call(this,t,r,"queryWzStatus")},invoke:function(t,r){return n.call(this,t,r,"invokeWz")
    }})}()):(m("card",{query:function(n,t){if(m.version_compare(m.version,"5.0")<0)return this;var r,e;m.isArray(n)?r=[JSON.stringify(n)]:(e=m.toArray(arguments),t=e.pop(),m.isFunction(t)?r=e:(r=m.toArray(arguments),t=null),r=[JSON.stringify(r)]);var o=function(n){m.isFunction(t)&&t(JSON.parse(n)),o=null
    };m.ios.invokeApp("cardMquery",{params:encodeURIComponent(r)},o)},add:function(n,t){if(m.version_compare(m.version,"5.0")<0)return this;var r,e;m.isString(n)?r=[n]:m.isArray(n)?r=[JSON.stringify(n)]:(e=m.toArray(arguments),t=e.pop(),m.isFunction(t)?r=e:(r=m.toArray(arguments),t=null),r=[JSON.stringify(r)]);
    var o=function(n){var r=JSON.parse(n),e=!1;for(var i in r){e=r[i].st;break}m.isFunction(t)&&t(e),o=null};return m.ios.invokeApp("cardMadd",{params:encodeURIComponent(r),gohome:"0"},o),!0}}),!function(){function n(n,t){if(f.version_compare(f.version,"5.3.0.0")<0)return this;var r=function(n){f.isFunction(t)&&t(JSON.parse(n)),r=null
    };n=JSON.stringify(n),f.ios.invokeApp("laopen",{params:encodeURIComponent(n)},r)}m("lightapp",{add:function(t,r){return n.call(this,t,r)},query:function(t,r){return n.call(this,t,r)},invoke:function(t,r){return n.call(this,t,r)}})}()),e("common:bdbox/utils/jsonToQuery",function(n,t,r,e){r.exports=function(n){if(e.isString(n))return n;
    var t=[];for(var r in n)t.push(r+"="+n[r]);return t.join("&")}}),e("common:bdbox/io/loadJS",function(r,e,o,i){function s(r,e,o){var s,u,d,l=t.createElement("script");i.isString(r)?(s=r,i.isFunction(e)&&(o=e,e=null)):(s=r.url,e=r.data,o=r.success,u=r.error||i.emptyFn,d=r.timeout),i.isObject(e)&&(e=c(e)),e&&(s+=(-1===s.indexOf("?")?"?":"&")+e),s=s.replace(/[&?]{1,2}/,"?");
    var f;/=\?/.test(s)&&(f="_box_jsonp"+i.getId(),s=s.replace(/=\?/,"="+f));var p=a();d=d||2e4,l.type="text/javascript",l.src=s;var m,v=!0,h=function(){f&&delete n[f],m&&clearTimeout(m),l.onload=l.onreadystatechange=l.onerror=null,l=null},b=function(){!l||l.readyState&&!/loaded|complete/.test(l.readyState)||(h(),v&&i.isFunction(o)&&o.apply(null,i.toArray(arguments)),v=!1)
    },g=function(n){h(),v&&u(n),v=!1};f&&(n[f]=b),m=setTimeout(function(){h(),v&&u("timeout"),v=!1},d),l.onload=l.onreadystatechange=l.onerror=b,l.onerror=g,p.appendChild(l)}function a(){return t.head||t.getElementsByTagName("head")[0]||t.documentElement}var c=r("common:bdbox/utils/jsonToQuery");i.emptyFn,o.exports=s
    }),e("common:bdbox/utils/queryToJson",function(n,t,r){r.exports=function(n){n=n?decodeURIComponent(n):"";var t=n.split("?"),r=t[1]?t[1]:t[0],e=r.split("&"),o={};return e.forEach(function(n){n=n.split("="),n[0].length>0&&(o[n[0]]=n[1]||"")}),o}}),e("common:bdbox/extend",function(n,t,r,e){function o(n,t,r){for(var e in t)r&&(i(t[e])||s(t[e]))?(i(t[e])&&!i(n[e])&&(n[e]={}),s(t[e])&&!s(n[e])&&(n[e]=[]),o(n[e],t[e],r)):c(t[e])||(n[e]=t[e])
    }var i=e.isPlainObject,s=e.isArray,a=e.isBoolean,c=e.isUndefined;r.exports=function(n){var t,r=e.emptyArr.slice.call(arguments,1);return a(n)&&(t=n,n=r.shift()),r.forEach(function(r){o(n,r,t)}),n}}),e("common:bdbox/monitor",function(t,r,e,o){var i=encodeURIComponent,s=function(n,t){n+=n.indexOf("?")<0?"?":"&",this.url=n,this.options=t
    };s.prototype.report=function(t){t=t||"";var r=new Image(1,1),e=[];if(o.isObject(t)){for(var s in t)e.push(s+"="+i(String(t[s])));t=e.join("&")}var a="_box_mt"+o.getId();n[a]=r,r.onload=r.onerror=r.onabort=function(){r.onload=r.onerror=r.onabort=null,n[a]=r=null};var c=this.url+t;return o.isFunction(this.options.customHandler)&&(c=this.options.customHandler(c)),r.src=c+"&_rnd="+Math.floor(2147483648*Math.random()),this
    },s.prototype.main=function(n,t){return n&&o.isFunction(this[n])&&this[n].apply(this,o.toArray(t||[])),this},e.exports=function(n,t){return new s(n,t)}}),e("common:bdbox/monitor/tc",function(n,t,r,e){var o=n("common:bdbox/monitor"),i=n("common:bdbox/extend"),s=n("common:bdbox/utils/queryToJson"),a=n("common:bdbox/utils/getVersion"),c=s(location.search),u=navigator.userAgent,d="//m.baidu.com/tcbox",l={service:"bdbox",action:"pblog",ctv:2,cen:"uid_ua_ut",data:{dataid:"2",actiontype:"1",actionid:"2",actiondata:{ref:c.ref||"",gmv:c.vmgdb||"",source:c.from||c.ref||"",boxVersion:a(),boxPlatform:u.match(/(iPad|iPhone|iPod)/gim)?"ios":"android"}}},f=encodeURIComponent;
    c.uid&&c.osname&&["osname","ua","ut","from","cfrom","uid","pkgname"].forEach(function(n){c[n]&&(l[n]=c[n])});var p=o(d,{customHandler:function(n){var t=[];for(var r in l)if(l.hasOwnProperty(r)){var o=l[r];e.isObject(o)&&(o=JSON.stringify(o)),t.push(r+"="+f(o))}return t.length&&(n+=t.join("&")),n}});p.init=function(n){l=n
    },p.pv=function(n,t){var r=l.data;r.actionid="1";var e={};return n&&(e.url=n),t&&(e.u=t),r.actiondata=i(r.actiondata,e),p.report()},p.tc=function(n,t){var r=l.data;return r.actionid="2",e.isPlainObject(n)?t=n:r.cateid=n+"",r.actiondata=i(r.actiondata,t),p.report()},p.event=function(n,t,r,e){if(!t)throw"monitor.tc.event need a evtName";
    var o={evtName:t,evtType:r||"",evtTag:e||""};return p.tc(n,o)},r.exports=function(){p.main.apply(p,arguments)}}),e("common:bdbox/moplus",function(n,t,r,e){var o=n("common:bdbox/utils/jsonToQuery"),i=n("common:bdbox/io/loadJS"),s=n("common:bdbox/utils/version_compare"),a=n("common:bdbox/monitor/tc"),c="com.baidu.searchbox",u="http://127.0.0.1:6259/",d="http://127.0.0.1:40310/",l="inapp_boxserver",f=500,p=null,m="__moplus_host__",v=1,h={ifSendPv:!1,ifSendEvt:{getHVersion:!1,sendintent:!1},ifHit:!1,setProb:function(n){v=n
    },check:function(){var n=!1,t=100,r=v;if(1>r){var e=(r+"").length,o=Math.pow(10,e-2);r*=o,t*=o}var i=parseInt(Math.random()*(t+1));return i>0&&r>=i&&(n=!0),n},parseUA:function(){var n,t,r=navigator.userAgent,e={uc:/UCBrowser\/(\S*) \S*/g,bd:/baidubrowser\/(\S*) \(Baidu/g,qq:/MQQBrowser\/(\S*) Mobile/g,chr:/Chrome\/(\S*) Mobile/g,qh:/360 Aphone Browser \((\S*)\)/g,sg:/SogouMobileBrowser\/(\S*)/g,mi:/MiuiBrowser\/(\S*)/g};
    for(var o in e){var i=e[o].exec(r);if(i){n=o,t=i[1];break}}return n=n?n:"other",t=t?t:"0",{t:n,v:t}},parsePro:function(){return"http:"===location.protocol?1:0},parseHost:function(){return b.curHost===d?1:0},sendPv:function(){this.ifHit&&!this.ifSendPv&&(this.ifSendPv=!0,a("pv"))},sendEvt:function(n){if(this.ifHit&&!this.ifSendEvt[n]){this.ifSendEvt[n]=!0;
    var t=this.parseUA(),r=t.t,e=t.v,o=this.parsePro(),i=this.parseHost();a("event",["2",n,{brName:r,brVer:e,isHttp:o,isNew:i}])}},init:function(){this.ifHit=this.check(),this.sendPv()}},b=function(n,t,r){this.isHttps="https:"===location.protocol,this.curHost=r||"",this.newHost=d,this.oldHost=this.isHttps?d:u,this.MCMDF=t||l,this._infoFuncs=[],this._verFuncs=[],this.minVersion=n?n:0,this.pkgName=c,h.init()
    };b.prototype={constructor:b,setMcmdf:function(n){return this.MCMDF=n,this},setHost:function(n){return this.curHost=n,this.setStorage(m,n),this},getHost:function(){return this.isHttps?(this.curHost=this.newHost,this.newHost):this.getStorage(m)?(this.curHost=this.getStorage(m),this.curHost):void 0},setStorage:function(n,t){sessionStorage.setItem(n,t)
    },getStorage:function(n){var t=sessionStorage.getItem(n);return t},api:function(n,t,r,s){if(!n)throw"Moplus.api need an action";e.isFunction(t)&&(s=r,r=t,t={});var a=n+(~n.indexOf("?")?"&":"?")+o(t);if(~a.indexOf("mcmdf")||(a+="&mcmdf="+this.MCMDF),h.sendEvt(n),this.getHost()){a=this.curHost+a;var c={url:a,timeout:s};
    e.isFunction(r)?(c.url+="&callback=?",c.success=r,c.error=function(){r({error:33})},i(c)):i(c)}else{var u=this.newHost+a,d=this.oldHost+a;e.isFunction(r)&&(u+="&callback=?",d+="&callback=?");var l={url:u,timeout:s},f={url:d,timeout:s},c={newData:l,oldData:f,success:r};this.request(c)}return this},getInfo:function(n,t){if(p)return n(p);
    if(this._infoFuncs.push(n),!(this._infoFuncs.length>1)){var r=this,e=function(n,t){t||(p=n);var e;for(t&&(n={error:33});e=r._infoFuncs.shift();)e(n)};if(this.getHost()){var o={url:this.curHost+"getsearchboxinfo?mcmdf="+this.MCMDF+"&callback=?",success:e,error:function(){e(null,!0)},timeout:t};i(o)}else{var s={url:this.newHost+"getsearchboxinfo?mcmdf="+this.MCMDF+"&callback=?",timeout:t},a={url:this.oldHost+"getsearchboxinfo?mcmdf="+this.MCMDF+"&callback=?",timeout:t},c={newData:s,oldData:a,success:e,error:function(){e(null,!0)
    }};this.request(c)}return this}},getHVersion:function(n,t){this._verFuncs.push(n);var r=this;if(!(this._verFuncs.length>1)){var e=function(n){var t;for(n=r.parseInfo(n);t=r._verFuncs.shift();)t(n)};return h.ifSendEvt.sendintent||h.sendEvt("getHVersion"),this.getInfo(e,t),this}},parseInfo:function(n,t){n=n||p,t=t||this.minVersion;
    var r=n.package_infos;if(!r||0===r.length)return!1;var e=c,o={offic:{name:c,version:0},oem:{version:0}};return r.forEach(function(n){var r=n.version_name,i=n.package_name;s(r,t)>=0&&(i===e?1===s(r,o.offic.version)&&(o.offic={version:r,name:c}):1===s(r,o.oem.version)&&(o.oem={version:r,name:i}))}),0===o.oem.version&&0===o.offic.version?!1:0!==o.offic.version?o.offic:0!==o.oem.version?o.oem:void 0
    },sendIntent:function(n,t,r){if(n&&e.isString(n))if(h.sendEvt("sendintent"),/^http/.test(n)||(n="sendintent?mcmdf="+this.MCMDF+"&callback=?&intent="+encodeURIComponent(n)),this.getHost()){var o={url:this.curHost+n,timeout:r};e.isFunction(t)?(o.success=function(n){n&&0===n.error&&h.sendEvt("sendintentOK"),t(n)
    },o.error=function(){t({error:33})}):o.success=function(n){n&&0===n.error&&h.sendEvt("sendintentOK")},i(o)}else{var s=this;this.getHVersion(function(o){if(o&&o.version){var a={url:s.curHost+n,timeout:r};e.isFunction(t)?(a.success=function(n){n&&0===n.error&&h.sendEvt("sendintentOK"),t(n)},a.error=function(){t({error:33})
    }):a.success=function(n){n&&0===n.error&&h.sendEvt("sendintentOK")},i(a)}})}return this},request:function(n){if(n&&"object"==typeof n){var t,r,o=this,s=n.newData,a=n.oldData,c=n.success,u=n.error;return s.success=function(n){"success"!==t&&(r&&clearTimeout(r),t="success",o.setHost(o.newHost),e.isFunction(c)&&c(n))
    },s.error=function(){"error"===t&&(e.isFunction(u)?u():e.isFunction(c)&&c({error:33})),t="error"},i(s),o.isHttps||(a.success=function(n){"success"!==t&&("error"===t?(t="success",o.setHost(o.oldHost),e.isFunction(c)&&c(n)):r=setTimeout(function(){t="success",o.setHost(o.oldHost),e.isFunction(c)&&c(n)},f))
    },a.error=function(){"error"===t&&(e.isFunction(u)?u():e.isFunction(c)&&c({error:33})),t="error"},i(a)),this}}},r.exports=function(n,t){return new b(n,t)},r.exports.Moplus=b}),f.version_compare(f.version,"5.3.5")>=0){var y,_={image:"imageUrl",url:"linkUrl",order:"mediaType"},x="";n[x]=f.emptyFn,"android"===f.os.name?(y=function(n){if(n.id&&f.byId(n.id)){var t=n.eventType||"touchstart";
    f.byId(n.id).addEventListener(t,function(){r(n)},!0)}var r=function(t){t=c(t||n);var r=t.error,e=t.success;t.iconUrl&&t.imageUrl&&delete t.imageUrl,f.android.invokeApp("Bdbox_android_utils","callShare",[JSON.stringify(t),e||"console.log",r||"console.log"])};return r},m("share",y)):(y=function(n){if(n.id&&f.byId(n.id)){var t=n.eventType||"touchstart";
    f.byId(n.id).addEventListener(t,function(){r(n)},!0)}var r=function(t){t=c(t||n);var r=t.error,e=t.success;t.iconUrl&&!t.imageUrl&&(t.imageUrl=t.iconUrl),t=JSON.stringify(t),f.ios.invokeApp("callShare",{options:encodeURIComponent(t),errorcallback:r||"console.log",successcallback:e||"console.log"})};return r
    },m("share",y))}else{var S=[],O=function(){m._socShare&&m._socShare.init?S.forEach(function(n){m._socShare.init(n)}):setTimeout(O,3e3)};f.io.loadJS("//m.baidu.com/static/searchbox/openjs/share.js?v=1.2",O);var A={source:"client_id",id:"dom_id",image:"pic_url",success:"afterRender"},y=function(n){var t={content:"",client_id:"ZVEpDSsmZ0qxa1gmgDAh1Fje",theme:"native",dom_id:"share",animate:!0,pic_url:"",url:encodeURIComponent(location.href)};
    return f.isObject(n)&&f.each(n,function(n,r){if(r in A&&(r=A[r]),"order"===r&&f.isArray(n)){var e=[];n.forEach(function(n){"email"===n&&(n="mail"),e.push(n)})}t[r]=n}),delete t.success,delete t.error,delete t.afterRender,"all"===t.order?t.order=["qqdenglu","sinaweibo","qqweibo","renren","kaixin","mail","sms"]:f.isString(t.order)&&(t.order=t.order.split(",")),m._socShare&&m._socShare.init?m._socShare.init(t):S.push(t),function(){m._socShare.ui._shareBtnClickHandler()
    }};m("share",y)}if(s(f,function(n,t){m[t]=n}),n.Box&&n.Box.$)for(var F in m)n.Box[F]=n.Box[F]||m[F];else n.Box=m}(window,document);

    return Box;
});
